### ISSUE TITLE
Gimbal instability/buzz detector

### ISSUE THREAD

**Issue by scanlime** [TucoFlyer/issues#3]
When the gimbal is having a bad time, we should be able to detect that and shut the gimbal down.

This is a separate task to fixing the underlying root causes of the instabilities. We need that, but we also need a kind of watchdog timer as a backup solution. That's what this will be.

**Comment by moriczgergo** [comment]
I think a method of this would be a state machine that knows the normal behaviour of all the variables of the gimbal. It could receive control data from Bot-Controller (or could be integrated into Bot-Controller) about the controls currently happening, and the state machine would be able to translate it to what the variables of the gimbal should be when this runs down. Also, thresholds would be needed to not get false-positives.

Other, more complicated method would be training an AI to handle the same duties as the state machine described above.

**Comment by scanlime** [comment]
This is just part of Bot-Controller, definitely no need for a separate
program... and yeah, the implementation method isn't really important right
now, it'll probably be some kind of state machine or set of thresholds or
whatever, the important part is determining the most effective measurements
to be making from the gimbal and how to time those measurements.

-m

**Comment by scanlime** [comment]
Done! After reverse engineering the firmware enough to locate the proper parameters to poll, this took the form of some statistics that track oscillation in the sampled motor currents from the gimbal.
